# Stage: Backend
FROM python:3.11-slim AS backend

# Set the working directory for the backend application
WORKDIR /app

# Install necessary packages for cryptography
RUN apt-get update && apt-get install -y build-essential libffi-dev libssl-dev

# Copy the requirements file into the container at /app
COPY ./api/requirements.txt /app/requirements.txt

# Install any necessary dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install bcrypt cryptography

# Copy the rest of the backend application code to /app
COPY ./api /app

# Set environment variables for database connection
ENV DATABASE_HOST=cmsc508.com
ENV DATABASE_USER=24fa_mussima
ENV DATABASE_PASSWORD=Shout4_mussima_JOY
ENV DATABASE_NAME=24fa_teams_24fa_fitlog

# Expose the backend port
EXPOSE 5002

# Run the Flask app
CMD ["python", "app.py"]
