version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-flask  # Updated to point to the correct Dockerfile for Flask
    ports:
      - "5002:5002"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Updated to point to the correct Dockerfile for React
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prtracker
      MYSQL_USER: $PRTRACKER_USER
      MYSQL_PASSWORD: $PRTRACKER_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
